services:
  laravel:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin